### ISSUE TITLE
Optional vars?

### ISSUE THREAD

**Issue by peteruithoven** [zaggino/brackets-snippets#17]
Currently when you leave a variable (`{{$...:...}}`) empty you can't insert the snippet. But sometimes you might want to leave parts empty. Maybe the following syntax could indicate a optional variable?
```
{{$...:...?}}
```
Like:
```
{{$1:indent?}}
```

**Comment by zaggino** [comment]
Good idea, I haven't been able to get back on development this after new year's but I'll definitely implement this one.

**Comment by peteruithoven** [comment]
Awesome!

**Comment by zaggino** [comment]
Please test the latest version `0.5.0` and provide feedback, thanks!

**Comment by peteruithoven** [comment]
How do I use this? I tried the following snippet: 
```
debug('{{$1:indent?}}{{$2:name}}: ',{{$3:value}});
```
But it still requires indent: 
![screen shot 2015-02-03 at 10 43 53](https://cloud.githubusercontent.com/assets/523210/6017777/af3782b4-ab91-11e4-9dbe-ee03a5a90e02.png)

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-snippets/blob/master/CHANGELOG.md
it's actually `{{$1?:optionalVariable}}`
the part after `:` is just a name to help user so it made more sense to put it to the main part

**Comment by peteruithoven** [comment]
Ah thanks. Works nice! 

Would be great if you could show the changelog to users after they update, but I understood there isn't something build into Brackets for that yet.

**Comment by zaggino** [comment]
Yes, my Git extension already does that with Changelog. I wanted to wait to do the same for this one until it's little more stable and mature.
