### ISSUE TITLE
Error on import Gist

### ISSUE THREAD

**Issue by marcelocostabr** [zaggino/brackets-snippets#2]
Hi, when I try to import my Gist returns a error "SyntaxError: Unexpected Token".

I double check the token and it´s correct.

Follow the image of error. 

Thank you amazing work.

![error](https://cloud.githubusercontent.com/assets/6169026/5131995/bad90e86-70df-11e4-8662-e9518517f658.PNG)

**Comment by WebSpectrum** [comment]
Does it still import Gists - I'm having trouble? Set up access token, import Gists > enter URL appears to die silently

**Comment by zaggino** [comment]
hi @WebSpectrum, this project is not maintained anymore
