### ISSUE TITLE
Readability in dark themes

### ISSUE THREAD

**Issue by peteruithoven** [zaggino/brackets-snippets#20]
Currently the snippets list is very hard to read in dark themes: 
![screen shot 2015-01-21 at 11 53 17](https://cloud.githubusercontent.com/assets/523210/5835053/5293487c-a164-11e4-82f4-b7fe14d79d72.png)

In light theme: 
![screen shot 2015-01-21 at 11 55 47](https://cloud.githubusercontent.com/assets/523210/5835066/78935ed6-a164-11e4-8cda-af921939ba44.png)

Maybe it should be more like this (text white-ish, background black or gray): 
![screen shot 2015-01-21 at 12 04 43](https://cloud.githubusercontent.com/assets/523210/5835173/bd9a5ccc-a165-11e4-965b-6391e58257bf.png)
![screen shot 2015-01-21 at 12 04 37](https://cloud.githubusercontent.com/assets/523210/5835172/bd99947c-a165-11e4-9161-e5036fb71e73.png)

This is how Brackets Git and Todo do this, although I'll admit it's not the same gui element, it's not selectable for example.

**Comment by zaggino** [comment]
Sure, will be fixed for the next version.

**Comment by zaggino** [comment]
Please test the latest version `0.5.0` and provide feedback, thanks!

**Comment by peteruithoven** [comment]
Very nice! 
![screen shot 2015-02-03 at 10 40 35](https://cloud.githubusercontent.com/assets/523210/6017735/238b7392-ab91-11e4-8483-f24193bb5d15.png)
