### ISSUE TITLE
choose among like named snippets by correlating file extension with lang metadata key

### ISSUE THREAD

**Issue by rhbecker** [zaggino/brackets-snippets#24]
Tangent inspired by issue #15 ...

Suppose I write code in a handful of languages, suppose I want to define a `function` snippet for each of those languages in order to align with standard coding conventions of each, and suppose I always want to invoke the version of function snippet appropriate to the language I'm coding in with a standard snippet trigger - say `function`.

I believe that trigger and file name are presently correlated. So I'd imagine I might need to put language-specific snippets into separately loaded snippet directories - e.g. ...

* /snippets/go/function
* /snippets/javascript/function
* /snippets/python/function

Given that you already support a `lang` metadata key, I was imagining that you could inspect the extension of the file from which a snippet trigger is invoked, compare that extension against a list of those known to be associated with the `lang` metadata key values applied to each of the `function` snippets, and therefore determine which of the snippets is being invoked. If you don't want to manage those lang-to-extension associations, you could instead introduce a metadata key in which the snippet author could define a comma-separated list of associated extensions.

If no lang / extension match is found, you could fall back to a function snippet without any extension association declarations, or lacking that, match to nothing - i.e. "no such snippet".

**Comment by zaggino** [comment]
This is implemented in the latest version 0.6.0.
See https://github.com/zaggino/brackets-snippets/tree/master/default_snippets
for js and php as an example

**Comment by rhbecker** [comment]
Great! Thanks! I'll try it out tomorrow.

**Comment by rhbecker** [comment]
Issue #26 has some relevant info about this change potentially breaking stuff. Ported over from that thread:

* Is `lang` now required?
* Could `lang` potentially recognize / accept an apply-to-all value, such as `*`?

**Comment by zaggino** [comment]
`lang` is not required and when not defined, snippet will appear for all files

**Comment by zaggino** [comment]
Version 0.6.1 has been published to the registry which fixes this.

**Comment by rhbecker** [comment]
0.6.1 verified to fix the issue when `lang` is not set. I also verified ...

* using the `f` snippet in a *.js file properly referenced the edition of the snippet marked with `##lang:js`
* using the `f` snippet in a *.php file properly referenced the edition of the snippet marked with `##lang:php`
* using the `f` snippet in an unsaved file (no extension) properly allowed me to decide which edition I wanted to use

Thanks!
